### ISSUE TITLE
Is simulation framework open source?

### ISSUE THREAD

**Issue by xiaoyulei** [heidihoward/ocaml-raft#1]
Hi, I read "ARC: Analysis of Raft Consensus", and notice that there is  a Simulation Framework to test raft in article.

Is the simulation framework open source? I only find the raft implementation, but not get the simulation framework software.

**Comment by videlalvaro** [comment]
Isn't this the simulator? https://github.com/heidi-ann/ocaml-raft/blob/master/lib/simulator.ml

**Comment by lia54** [comment]
Hi there! @xiaoyulei @videlalvaro @heidihoward 
Have any of you been able to compile and run the simulator?

**Comment by heidihoward** [comment]
Yes, the simulator is built-in. Unfortunately, I long ago abandoned this effort due to a lack of interest. I'd suggest looking at [OCons](https://github.com/Cjen1/OCons) for a more up-to-date consensus simulator in OCaml.
