### ISSUE TITLE
Help to install libraries, build and run the ocaml-raft simulator

### ISSUE THREAD

**Issue by lia54** [heidihoward/ocaml-raft#2]
Hi, 

I was trying to build and run the simulator and I was having problems to compile the ocaml files.
After running `make` in the project directory, I got the following error:

```
+ ocamlfind ocamldep -package core,sexplib.syntax,bin_prot.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax,async -syntax camlp4o -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core -modules spl/raftMonitor.mli > spl/raftMonitor.mli.depends
ocamlfind: Package `async' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
+ ocamlfind ocamldep -package core,sexplib.syntax,bin_prot.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax,async -syntax camlp4o -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core -modules test/test_splaytree.ml > test/test_splaytree.ml.depends
ocamlfind: Package `async' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
```

I checked online and it seams that the async_extra, which is dependent package is not supported anymore in the current versions of the core module. 
Is there any environment you have used before to run the simulator such as a VM or a container that can be shared with all the needed libraries and dependencies for ocaml to run?

Do you have any suggestions on how to fix this problem? 
@heidihoward

**Comment by heidihoward** [comment]
Nope sorry. It's been too many years since I ran this. I'd suggest looking at [OCons](https://github.com/Cjen1/OCons) for a more up-to-date consensus simulator in OCaml.

**Comment by lia54** [comment]
Hi @heidihoward 
Thanks! I'll take a look at it, but it seems like it only has Paxos implemented and not Raft.
Also, do you know of any other discrete event simulators for consensus implemented in a language other than OCaml?

**Comment by heidihoward** [comment]
I thought it had both. You might find more consensus simulators here: https://github.com/heidihoward/distributed-consensus-reading-list

**Comment by lia54** [comment]
I found this [PR](https://github.com/Cjen1/OCons/pull/20) in [Ocons](https://github.com/Cjen1/OCons) repo with Raft implemented. Thanks!
I checked the reading list, but I only found full system implementation papers.
